<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MedicalConsulting.Application\MedicalConsulting.Application.csproj" />
    <ProjectReference Include="..\MedicalConsulting.Domain\MedicalConsulting.Domain.csproj" />
    <ProjectReference Include="..\MedicalConsulting.Infrastructure\MedicalConsulting.Infrastructure.csproj" />
  </ItemGroup>
</Project>
